# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
# xcode_workspace: ./Example/SwiftyMavenlink.xcworkspace
# cache: cocoapods
# podfile: ./Example/Podfile
before_install:
- brew install xctool
script:
 - xctool -workspace ./Example/SwiftyMavenlink.xcworkspace -scheme SwiftyMavenlink-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 # xctool doesn't support the required code coverage params yet, so use xcodebuild to run tests
 - xcodebuild -scheme SwiftyMavenlink-Example -workspace ./Example/SwiftyMavenlink.xcworkspace -sdk iphonesimulator test -enableCodeCoverage YES
 - pod lib lint --allow-warnings
after_success:
 - bash <(curl -s https://codecov.io/bash)
